### ISSUE TITLE
Bug server starting database (importing exercises) - Radiogram

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-sam/digital-fuesim-manv#1046]
The following error accours after a while of importing:
```

digital-fuesim-manv       | 2023-09-15T10:37:09.051723510Z ❌ An error occurred while loading exercises.
digital-fuesim-manv       | 2023-09-15T10:37:09.054184795Z Error while restoring exercise `0b677701-e4f3-4a07-9798-b4683964b2ab`: Failed to restore exercise `0b677701-e4f3-4a07-9798-b4683964b2ab`: A reducer error occurred while restoring (Action 1495: `{"type":"[Radiogram] Accept radiogram","clientId":"fe5e3bee-0840-42e3-8a87-5efcc2c71080","radiogramId":"ec58f938-91da-479d-a4bc-a6c99ad1f48c"}`) Error: Failed to restore exercise `0b677701-e4f3-4a07-9798-b4683964b2ab`: A reducer error occurred while restoring (Action 1495: `{"type":"[Radiogram] Accept radiogram","clientId":"fe5e3bee-0840-42e3-8a87-5efcc2c71080","radiogramId":"ec58f938-91da-479d-a4bc-a6c99ad1f48c"}`)
digital-fuesim-manv       | 2023-09-15T10:37:09.054247636Z     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:235:27
digital-fuesim-manv       | 2023-09-15T10:37:09.054251704Z     at Array.forEach (<anonymous>)
digital-fuesim-manv       | 2023-09-15T10:37:09.054255040Z     at ExerciseWrapper.restoreState (file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:228:37)
digital-fuesim-manv       | 2023-09-15T10:37:09.054257876Z     at ExerciseWrapper.restore (file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:218:14)
digital-fuesim-manv       | 2023-09-15T10:37:09.054260932Z     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:282:56
digital-fuesim-manv       | 2023-09-15T10:37:09.054263687Z     at Array.map (<anonymous>)
digital-fuesim-manv       | 2023-09-15T10:37:09.054266413Z     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:282:23
digital-fuesim-manv       | 2023-09-15T10:37:09.054269088Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digital-fuesim-manv       | 2023-09-15T10:37:09.054271823Z     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:73:28)
digital-fuesim-manv       | 2023-09-15T10:37:09.054274598Z     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31) ReducerError: Radiogram with id ec58f938-91da-479d-a4bc-a6c99ad1f48c does not exist
digital-fuesim-manv       | 2023-09-15T10:37:09.054277423Z     at getExerciseRadiogramById (file:///usr/local/app/shared/dist/store/action-reducers/utils/get-element.js:30:15)
digital-fuesim-manv       | 2023-09-15T10:37:09.054295027Z     at acceptRadiogram (file:///usr/local/app/shared/dist/models/radiogram/radiogram-helpers-mutable.js:14:23)
digital-fuesim-manv       | 2023-09-15T10:37:09.054298063Z     at Object.reducer (file:///usr/local/app/shared/dist/store/action-reducers/radiogram.js:84:13)
digital-fuesim-manv       | 2023-09-15T10:37:09.054300819Z     at applyAction (file:///usr/local/app/shared/dist/store/reduce-exercise-state.js:27:54)
digital-fuesim-manv       | 2023-09-15T10:37:09.054303524Z     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:231:32
digital-fuesim-manv       | 2023-09-15T10:37:09.054306199Z     at Array.forEach (<anonymous>)
digital-fuesim-manv       | 2023-09-15T10:37:09.054309926Z     at ExerciseWrapper.restoreState (file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:228:37)
digital-fuesim-manv       | 2023-09-15T10:37:09.054312671Z     at ExerciseWrapper.restore (file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:218:14)
digital-fuesim-manv       | 2023-09-15T10:37:09.054315376Z     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:282:56
digital-fuesim-manv       | 2023-09-15T10:37:09.054318081Z     at Array.map (<anonymous>)
digital-fuesim-manv exited with code 0

```

This happens on the main branch (fuesim-manv.de).
Try to save the database, if someone wants to look at it.

**Comment by lukasrad02** [comment]
If the database export is still available, I would be happy to take a look into this.

However, I would expect this bug to be caused by the problem described in #874 (TL;DR: With the current simulation architecture, we cannot ensure backwards compatibility of exercises that have been started. Only non-started exercises are guaranteed to be importable in newer versions.).

Of course, we should change the behavior of the backend so that it can starts even if some exercise could not be imported. The failure can (and should) be logged, but should not prevent startup.

**Comment by christianschaeffer** [comment]
> However, I would expect this bug to be caused by the problem described in [#874](https://github.com/hpi-sam/digital-fuesim-manv/issues/874) (TL;DR: With the current simulation architecture, we cannot ensure backwards compatibility of exercises that have been started. Only non-started exercises are guaranteed to be importable in newer versions.).

Good call, this seems plausible.

As a quick fix, could we have a warning popup when exporting a running simulation exercise (or even prevent export of them alltogether)?

**Comment by lukasrad02** [comment]
> As a quick fix, could we have a warning popup when exporting a running simulation exercise?

I think in general it makes sense to add this, but it won't help against the server crashes, as they caused by the automatic saves to the database

**Comment by anonym-HPI** [comment]
> If the database export is still available, I would be happy to take a look into this.
> 
> However, I would expect this bug to be caused by the problem described in [#874](https://github.com/hpi-sam/digital-fuesim-manv/issues/874) (TL;DR: With the current simulation architecture, we cannot ensure backwards compatibility of exercises that have been started. Only non-started exercises are guaranteed to be importable in newer versions.).
> 
> Of course, we should change the behavior of the backend so that it can starts even if some exercise could not be imported. The failure can (and should) be logged, but should not prevent startup.

Not sure if this is possible right now (would have to look again into what "export current state" does), but allowing to export an exercise in the state before it was started, would probably be a good way of handling compatibility issues. I am thinking of some trainer sitting there 1 hour and developing something. Pressing shortly start to see if it works and then exporting. Later he tries to import it again and is incompatible. So a button to export only the situation before he pressed start would be a good way (with explaination that this will be compatible with feature versions).
