### ISSUE TITLE
Backend in container fails after a while

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-sam/digital-fuesim-manv#451]
Found this in the logs on the feature/395-tragetrupps-carrying-unit branch, that was used for BABZ
<details>
  <summary>docker compose logs --tail=200 digital-fuesim-manv-exp</summary>

```
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
digital-fuesim-manv-exp  | npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  | npm WARN logfile   errno: -13,
digital-fuesim-manv-exp  | npm WARN logfile   code: 'EACCES',
digital-fuesim-manv-exp  | npm WARN logfile   syscall: 'scandir',
digital-fuesim-manv-exp  | npm WARN logfile   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile }
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 typeorm:cli:prod
digital-fuesim-manv-exp  | > NODE_ENV=migration node --experimental-specifier-resolution=node ./node_modules/typeorm/cli -d dist/src/database/migration-datasource.js "migration:run"
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | (node:38) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
digital-fuesim-manv-exp  | npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  | npm WARN logfile   errno: -13,
digital-fuesim-manv-exp  | npm WARN logfile   code: 'EACCES',
digital-fuesim-manv-exp  | npm WARN logfile   syscall: 'scandir',
digital-fuesim-manv-exp  | npm WARN logfile   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile }
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 typeorm:cli:prod
digital-fuesim-manv-exp  | > NODE_ENV=migration node --experimental-specifier-resolution=node ./node_modules/typeorm/cli -d dist/src/database/migration-datasource.js "migration:run"
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | (node:38) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
digital-fuesim-manv-exp  | npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  | npm WARN logfile   errno: -13,
digital-fuesim-manv-exp  | npm WARN logfile   code: 'EACCES',
digital-fuesim-manv-exp  | npm WARN logfile   syscall: 'scandir',
digital-fuesim-manv-exp  | npm WARN logfile   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile }
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 typeorm:cli:prod
digital-fuesim-manv-exp  | > NODE_ENV=migration node --experimental-specifier-resolution=node ./node_modules/typeorm/cli -d dist/src/database/migration-datasource.js "migration:run"
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | (node:38) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
```
</details>

The container is still running, but the backend does not work anymore.
Also the normal dev container is in mode `restarting`:

<details>
  <summary>dev container, message repeating itself_</summary>

```
digital-fuesim-manv-dev  |
digital-fuesim-manv-dev  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-dev  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-dev  |
digital-fuesim-manv-dev  |
```
</details>

**Comment by Dassderdie** [comment]
My guess:

We had an exercise running the whole time over (= every second a tick action). - A day has 86400 seconds. So we call at the specified code lines splice with more than 65536 arguments.

```
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
```

https://stackoverflow.com/a/44978433/12698757

> But beware: by using apply this way, you run the risk of exceeding the JavaScript engine's argument length limit. The consequences of applying a function with too many arguments (that is, more than tens of thousands of arguments) varies across engines. (The JavaScriptCore engine has hard-coded [argument limit of 65536](https://bugs.webkit.org/show_bug.cgi?id=80797).
> 
> This is because the limit (and indeed, even the nature of any excessively-large-stack behavior) is unspecified. Some engines will throw an exception. More perniciously, others will arbitrarily limit the number of arguments actually passed to the applied function. To illustrate this latter case: if such an engine had a limit of four arguments (actual limits are of course significantly higher), it would be as if the arguments 5, 6, 2, 3 had been passed to apply in the examples above, rather than the full array.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#using_apply_and_built-in_functions


We could prevent that by maybe using `concat` instead?

**Comment by ClFeSc** [comment]
@Dassderdie Could be. I'll look into the database in (hopefully) short time.

**Comment by Dassderdie** [comment]
On second thought: `Concat` won't work because it doesn't mutate the array...

**Comment by ClFeSc** [comment]
@Dassderdie You're probably right. There are exercises with more than 750,000 ticks. My guess would be to `push` them one by one into the array, although this would probably be painfully slow. Do you know any push-range method that takes an array?

**Comment by ClFeSc** [comment]
This could also happen on import, as we're using `push(...actions)` there.

**Comment by Dassderdie** [comment]
And good to know that we don't seem to have a big memory leak. Else the server would have crashed before the restore (with in total more than a million actions)

**Comment by ClFeSc** [comment]
> You could do it the same as currently, but make a loop and only take chunks of e.g. 50000 items per iteration.

Good point. I can write something to handle that.

> Btw. Why does the array have to be read-only?

I thought that it wouldn't be that great to have a public, writable array for this. But I could also do a private setter I think. Probably even better than splicing or pushing.

**Comment by ClFeSc** [comment]
> And good to know that we don't seem to have a big memory leak. Else the server would have crashed before the restore (with in total more than a million actions)

Actually, we can't certainly know why the container restarted in the first place. Probably due to the watchtower, but it could also be that the container crashed and then entered the current restart loop.

**Comment by Dassderdie** [comment]
> > And good to know that we don't seem to have a big memory leak. Else the server would have crashed before the restore (with in total more than a million actions)
> 
> Actually, we can't certainly know why the container restarted in the first place. Probably due to the watchtower, but it could also be that the container crashed and then entered the current restart loop.

But no actions would be added after the server crashed once, correct?

Then we know for sure that the server was able to run with at least 750,000 actions in an exercise because the restart loop only began after this amount of actions was already there.
