### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#579]
This is mainly focused on `pg` in the `backend` that should not be required directly anywhere but can serve as an entry point into looking at the dependencies and removing the ones that are not needed.

**Comment by Dassderdie** [comment]
I think it isn't enough to just remove it from the `package.json` and run `npm i`. Instead, try to also delete the `node_modules` and `package-lock.json` before you run `npm i`.

```
C:\Users\julia\OneDrive\Dokumente\Studium\digital-fuesim-manv\backend\node_modules\typeorm\src\driver\postgres\PostgresDriver.ts:1441
            throw new DriverPackageNotInstalledError("Postgres", "pg")
                  ^
DriverPackageNotInstalledError: Postgres package has not been found installed. Try to install it: npm install pg --save
    at PostgresDriver.loadDependencies (C:\Users\julia\OneDrive\Dokumente\Studium\digital-fuesim-manv\backend\node_modules\typeorm\src\driver\postgres\PostgresDriver.ts:1441:19)
    at new PostgresDriver (C:\Users\julia\OneDrive\Dokumente\Studium\digital-fuesim-manv\backend\node_modules\typeorm\src\driver\postgres\PostgresDriver.ts:304:14)
    at DriverFactory.create (C:\Users\julia\OneDrive\Dokumente\Studium\digital-fuesim-manv\backend\node_modules\src\driver\DriverFactory.ts:36:24)
    at new DataSource (C:\Users\julia\OneDrive\Dokumente\Studium\digital-fuesim-manv\backend\node_modules\src\data-source\DataSource.ts:139:43)
    at createNewDataSource (file:///C:/Users/julia/OneDrive/Dokumente/Studium/digital-fuesim-manv/backend/src/database/data-source.ts:16:12)
    at main (file:///C:/Users/julia/OneDrive/Dokumente/Studium/digital-fuesim-manv/backend/src/index.ts:14:24)
    at file:///C:/Users/julia/OneDrive/Dokumente/Studium/digital-fuesim-manv/backend/src/index.ts:69:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ClFeSc** [comment]
I think this issue was created with a false assumption in mind.
